name = "BasisMatrices"
uuid = "f80922ce-2d1d-4c24-aded-05b297dedb96"
authors = ["Spencer Lyon <spencer.lyon@stern.nyu.edu>"]
version = "0.6.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
QuantEcon = "fcd29c91-0bd7-5a09-975d-7ac3f643a60c"
